-- =============================================================================
-- Maydi's — CLEAN bootstrap (run once on a fresh or reset database)
-- Source of truth for schema used by apps/website
-- =============================================================================

create extension if not exists "pgcrypto";

-- ─── Tables ──────────────────────────────────────────────────────────────────

drop table if exists public.reservations cascade;
drop table if exists public.menu_items cascade;

create table public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  details text not null default '',
  price text not null,
  category text not null,
  image_url text not null default '',
  tags text[] not null default '{}',
  sort_order int not null default 0,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  email text,
  date date not null,
  time text not null,
  guests text not null,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index menu_items_category_idx on public.menu_items (category);
create index menu_items_sort_idx on public.menu_items (sort_order);
create index reservations_date_idx on public.reservations (date desc);
create index reservations_status_idx on public.reservations (status);

-- ─── Privileges (Data API roles) ─────────────────────────────────────────────

grant usage on schema public to postgres, anon, authenticated, service_role;

grant select on table public.menu_items to anon, authenticated, service_role;
grant all on table public.menu_items to service_role;

grant insert on table public.reservations to anon, authenticated, service_role;
grant all on table public.reservations to service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter default privileges in schema public
  grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public
  grant usage, select on sequences to anon, authenticated, service_role;

-- ─── RLS ─────────────────────────────────────────────────────────────────────

alter table public.menu_items enable row level security;
alter table public.reservations enable row level security;

create policy "anon_read_menu"
  on public.menu_items for select
  to anon, authenticated
  using (available = true);

create policy "service_all_menu"
  on public.menu_items for all
  to service_role
  using (true) with check (true);

create policy "anon_insert_reservations"
  on public.reservations for insert
  to anon, authenticated
  with check (true);

create policy "service_all_reservations"
  on public.reservations for all
  to service_role
  using (true) with check (true);

-- ─── RPC: create_reservation(payload jsonb) ──────────────────────────────────
-- Preferred write path for /api/reserve (SECURITY DEFINER)

drop function if exists public.create_reservation(jsonb);
drop function if exists public.create_reservation(text, text, text, date, text, text, text);

create or replace function public.create_reservation(payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  v_name text := trim(coalesce(payload->>'name', ''));
  v_phone text := trim(coalesce(payload->>'phone', ''));
  v_email text := nullif(trim(coalesce(payload->>'email', '')), '');
  v_date date;
  v_time text := trim(coalesce(payload->>'time', ''));
  v_guests text := trim(coalesce(payload->>'guests', ''));
  v_notes text := nullif(trim(coalesce(payload->>'notes', '')), '');
begin
  begin
    v_date := (payload->>'date')::date;
  exception when others then
    raise exception 'invalid date';
  end;

  if v_name = '' then raise exception 'name is required'; end if;
  if v_phone = '' then raise exception 'phone is required'; end if;
  if v_date is null then raise exception 'date is required'; end if;
  if v_time = '' then raise exception 'time is required'; end if;
  if v_guests = '' then raise exception 'guests is required'; end if;

  insert into public.reservations (name, phone, email, date, time, guests, notes, status)
  values (v_name, v_phone, v_email, v_date, v_time, v_guests, v_notes, 'pending')
  returning id into new_id;

  return new_id;
end;
$$;

revoke all on function public.create_reservation(jsonb) from public;
grant execute on function public.create_reservation(jsonb) to anon, authenticated, service_role;

-- ─── RPC: get_menu_items() ───────────────────────────────────────────────────

drop function if exists public.get_menu_items();

create or replace function public.get_menu_items()
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', m.id,
        'name', m.name,
        'description', m.description,
        'details', m.details,
        'price', m.price,
        'category', m.category,
        'image_url', m.image_url,
        'tags', to_jsonb(m.tags),
        'sort_order', m.sort_order
      )
      order by m.sort_order asc, m.id asc
    ),
    '[]'::jsonb
  )
  from public.menu_items m
  where coalesce(m.available, true) = true;
$$;

revoke all on function public.get_menu_items() from public;
grant execute on function public.get_menu_items() to anon, authenticated, service_role;

-- ─── Seed menu ───────────────────────────────────────────────────────────────

insert into public.menu_items (name, description, details, price, category, image_url, tags, sort_order) values
  ('Maydi''s Signature Brunch', 'Poached eggs, smoked salmon, silky avocado on toasted sourdough', 'Two perfectly poached eggs over smoked salmon and avocado on sourdough.', '950 DA', 'Brunch', '/images/gallery-01.jpg', array['Chef''s Pick','Bestseller'], 1),
  ('Garden Eggs Platter', 'Roasted seasonal vegetables, herb pesto, two poached eggs', 'Roasted vegetables crowned with poached eggs and basil pesto.', '850 DA', 'Brunch', '/images/gallery-02.jpg', array['Vegetarian'], 2),
  ('Brioche French Toast', 'Thick-cut brioche, vanilla custard, maple syrup, fresh berries', 'Brioche soaked in vanilla custard, pan-fried golden.', '750 DA', 'Brunch', '/images/gallery-04.jpg', array['Sweet'], 3),
  ('Avocado Toast Deluxe', 'Sourdough, smashed avocado, cherry tomatoes, za''atar, chilli', 'Seasoned avocado mash on sourdough with tomatoes and za''atar.', '650 DA', 'Toasts & Croissants', '/images/gallery-07.jpg', array['Vegan','Bestseller'], 4),
  ('Butter Croissant', 'Freshly baked daily, served warm with house-made jam', 'Laminated with French butter, baked fresh each morning.', '350 DA', 'Toasts & Croissants', '/images/gallery-08.jpg', array['Fresh Daily'], 5),
  ('Green Goddess Bowl', 'Tri-colour quinoa, avocado, cucumber, herbs, green tahini', 'Nourishing quinoa bowl with green tahini and seeds.', '850 DA', 'Salads & Bowls', '/images/gallery-09.jpg', array['Vegan','Gluten-Free'], 6),
  ('Chocolate Fondant', 'Warm dark chocolate, molten centre, vanilla bean ice cream', '72% dark chocolate fondant with vanilla ice cream.', '650 DA', 'Desserts & Cakes', '/images/gallery-10.jpg', array['Warm','Bestseller'], 7),
  ('Ceremonial Matcha Latte', 'Ceremonial grade matcha, steamed oat milk, touch of raw honey', 'Japanese matcha with oat milk, hot or iced.', '450 DA', 'Beverages', '/images/unnamed.webp', array['Vegan Option'], 8),
  ('House Specialty Coffee', 'Single origin, prepared your way', 'Ethiopian single-origin espresso, flat white, or cold brew.', '300 DA', 'Beverages', '/images/unnamed-1.webp', array[]::text[], 9);

-- ─── Reload API cache ────────────────────────────────────────────────────────

notify pgrst, 'reload schema';
notify pgrst, 'reload config';

-- ─── Verify (you should see rows) ────────────────────────────────────────────

select 'menu_items' as object, count(*)::text as value from public.menu_items
union all
select 'functions', string_agg(proname, ', ')
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public' and proname in ('create_reservation', 'get_menu_items');
