-- =============================================================================
-- 002 — Full menu seed (production density)
-- Safe to re-run: replaces menu_items only (reservations untouched).
-- Catalog = 16 dishes × 3 copies = 48 rows (duplicates OK for grid density).
-- =============================================================================

truncate table public.menu_items restart identity;

insert into public.menu_items (name, description, details, price, category, image_url, tags, sort_order) values
  ('Maydi''s Signature Brunch', 'Poached eggs, smoked salmon, silky avocado on toasted sourdough', 'Two perfectly poached eggs draped over house-smoked salmon and silky avocado mash on toasted sourdough. Finished with a drizzle of lemon herb oil, capers, and microgreens. Served with a side dressed salad.', '950 DA', 'Brunch', '/images/gallery-01.jpg', array['Chef''s Pick','Bestseller'], 1),
  ('Garden Eggs Platter', 'Roasted seasonal vegetables, herb pesto, two poached eggs', 'A colourful medley of oven-roasted courgette, peppers, and cherry tomatoes, crowned with two poached eggs and a vibrant basil-pistachio pesto. Light, nourishing, and deeply satisfying.', '850 DA', 'Brunch', '/images/gallery-02.jpg', array['Vegetarian'], 2),
  ('Brioche French Toast', 'Thick-cut brioche, vanilla custard, maple syrup, fresh berries', 'Thick-cut brioche soaked overnight in a vanilla bean egg custard, pan-fried to a golden blush, served with warm maple syrup, a dusting of icing sugar, and a generous spoonful of seasonal berry compote.', '750 DA', 'Brunch', '/images/gallery-04.jpg', array['Sweet'], 3),
  ('Avocado Toast Deluxe', 'Sourdough, smashed avocado, cherry tomatoes, za''atar, chilli', 'Thick sourdough slices toasted to perfection, spread with seasoned avocado mash, halved cherry tomatoes, toasted pine nuts, and a flourish of za''atar. A squeeze of lemon ties it all together.', '650 DA', 'Toasts & Croissants', '/images/gallery-07.jpg', array['Vegan','Bestseller'], 4),
  ('Salmon Cream Cheese Toast', 'Whipped cream cheese, cold-smoked salmon, capers, dill', 'House-baked rye toast spread with whipped cream cheese blended with fresh dill, topped with silky cold-smoked salmon, briny capers, pickled red onion, and a crack of black pepper.', '700 DA', 'Toasts & Croissants', '/images/gallery-08.jpg', array[]::text[], 5),
  ('Butter Croissant', 'Freshly baked daily, served warm with house-made jam', 'Laminated in house with 84% French butter over three days. Baked fresh each morning until deeply golden. Served warm alongside house-made apricot jam and a curl of salted butter.', '350 DA', 'Toasts & Croissants', '/images/gallery-09.jpg', array['Fresh Daily'], 6),
  ('Almond Frangipane Croissant', 'Double-baked, almond cream filling, toasted flaked almonds', 'Our croissant taken one step further — filled with rich almond frangipane, double-baked for crisp caramelised layers, finished with toasted flaked almonds and a cloud of icing sugar.', '450 DA', 'Toasts & Croissants', '/images/gallery-10.jpg', array['Chef''s Pick'], 7),
  ('Green Goddess Bowl', 'Tri-colour quinoa, avocado, cucumber, herbs, green tahini', 'A nourishing base of tri-colour quinoa topped with sliced avocado, cucumber ribbons, roasted chickpeas, fresh herbs, and a house-made green tahini dressing, scattered with seeds and edible flowers.', '850 DA', 'Salads & Bowls', '/images/unnamed.webp', array['Vegan','Gluten-Free'], 8),
  ('Mediterranean Feta Salad', 'Rocket, sheep''s feta, Kalamata olives, cherry tomatoes, herbs', 'A generous tangle of rocket and mixed leaves, Kalamata olives, halved cherry tomatoes, and thin-sliced cucumber, topped with crumbled sheep''s milk feta and dressed with lemon, extra virgin olive oil, and wild oregano.', '750 DA', 'Salads & Bowls', '/images/unnamed-1.webp', array['Vegetarian'], 9),
  ('Warm Roasted Grain Bowl', 'Farro, roasted vegetables, hummus, hazelnut dukkah', 'Warm farro and bulgur wheat topped with a rainbow of oven-roasted seasonal vegetables, a generous swoosh of house-made hummus, hazelnut dukkah, pomegranate molasses, and a handful of fresh herbs.', '800 DA', 'Salads & Bowls', '/images/unnamed-2.webp', array['Vegan'], 10),
  ('Chocolate Fondant', 'Warm dark chocolate, molten centre, vanilla bean ice cream', 'Individually baked 72% dark chocolate fondant — crackled on the outside, richly flowing within. Served immediately alongside a quenelle of house-made vanilla bean ice cream and a dusting of cacao.', '650 DA', 'Desserts & Cakes', '/images/unnamed-3.webp', array['Warm','Bestseller'], 11),
  ('Lotus Biscoff Cheesecake', 'Velvety baked cheesecake, Biscoff crust, caramel glaze', 'Velvety baked cheesecake on a buttery Lotus Biscoff crust, topped with a mirror-smooth caramel glaze and a whole Biscoff biscuit. Chilled overnight for a perfectly set, melt-in-the-mouth texture.', '700 DA', 'Desserts & Cakes', '/images/sealing.webp', array['Chef''s Pick'], 12),
  ('Pistachio & Raspberry Tart', 'Crisp pastry shell, pistachio frangipane, fresh raspberries', 'A crisp pâte sucrée shell filled with silky pistachio frangipane cream, adorned with fresh raspberries and a thin coat of apricot glaze. Finished with chopped pistachios and a sprig of fresh mint.', '600 DA', 'Desserts & Cakes', '/images/gallery-01.jpg', array['Seasonal'], 13),
  ('Ceremonial Matcha Latte', 'Ceremonial grade matcha, steamed oat milk, touch of raw honey', 'Premium ceremonial grade Japanese matcha, whisked to a smooth froth and topped with steamed oat milk poured in a delicate pattern. Subtly sweetened with raw honey. Available hot or iced.', '450 DA', 'Beverages', '/images/gallery-02.jpg', array['Vegan Option'], 14),
  ('Iced Hibiscus Rose', 'Hibiscus, rose water, fresh mint, lemon, sparkling water', 'A jewel-bright, naturally caffeine-free sipper. Cold-steeped hibiscus blended with rose water, fresh lemon, and a handful of mint, poured over ice and topped with a splash of sparkling water.', '350 DA', 'Beverages', '/images/gallery-04.jpg', array['Caffeine-Free','Bestseller'], 15),
  ('House Specialty Coffee', 'Single origin, prepared your way — espresso, flat white, cold brew', 'Sourced from single-origin Ethiopian beans, roasted to a medium-light profile. Available as espresso, flat white, cappuccino, Americano, or cold brew. All dairy and plant milks available.', '300 DA', 'Beverages', '/images/gallery-07.jpg', array[]::text[], 16),
  ('Maydi''s Signature Brunch', 'Poached eggs, smoked salmon, silky avocado on toasted sourdough', 'Two perfectly poached eggs draped over house-smoked salmon and silky avocado mash on toasted sourdough. Finished with a drizzle of lemon herb oil, capers, and microgreens. Served with a side dressed salad.', '950 DA', 'Brunch', '/images/gallery-01.jpg', array['Chef''s Pick','Bestseller'], 17),
  ('Garden Eggs Platter', 'Roasted seasonal vegetables, herb pesto, two poached eggs', 'A colourful medley of oven-roasted courgette, peppers, and cherry tomatoes, crowned with two poached eggs and a vibrant basil-pistachio pesto. Light, nourishing, and deeply satisfying.', '850 DA', 'Brunch', '/images/gallery-02.jpg', array['Vegetarian'], 18),
  ('Brioche French Toast', 'Thick-cut brioche, vanilla custard, maple syrup, fresh berries', 'Thick-cut brioche soaked overnight in a vanilla bean egg custard, pan-fried to a golden blush, served with warm maple syrup, a dusting of icing sugar, and a generous spoonful of seasonal berry compote.', '750 DA', 'Brunch', '/images/gallery-04.jpg', array['Sweet'], 19),
  ('Avocado Toast Deluxe', 'Sourdough, smashed avocado, cherry tomatoes, za''atar, chilli', 'Thick sourdough slices toasted to perfection, spread with seasoned avocado mash, halved cherry tomatoes, toasted pine nuts, and a flourish of za''atar. A squeeze of lemon ties it all together.', '650 DA', 'Toasts & Croissants', '/images/gallery-07.jpg', array['Vegan','Bestseller'], 20),
  ('Salmon Cream Cheese Toast', 'Whipped cream cheese, cold-smoked salmon, capers, dill', 'House-baked rye toast spread with whipped cream cheese blended with fresh dill, topped with silky cold-smoked salmon, briny capers, pickled red onion, and a crack of black pepper.', '700 DA', 'Toasts & Croissants', '/images/gallery-08.jpg', array[]::text[], 21),
  ('Butter Croissant', 'Freshly baked daily, served warm with house-made jam', 'Laminated in house with 84% French butter over three days. Baked fresh each morning until deeply golden. Served warm alongside house-made apricot jam and a curl of salted butter.', '350 DA', 'Toasts & Croissants', '/images/gallery-09.jpg', array['Fresh Daily'], 22),
  ('Almond Frangipane Croissant', 'Double-baked, almond cream filling, toasted flaked almonds', 'Our croissant taken one step further — filled with rich almond frangipane, double-baked for crisp caramelised layers, finished with toasted flaked almonds and a cloud of icing sugar.', '450 DA', 'Toasts & Croissants', '/images/gallery-10.jpg', array['Chef''s Pick'], 23),
  ('Green Goddess Bowl', 'Tri-colour quinoa, avocado, cucumber, herbs, green tahini', 'A nourishing base of tri-colour quinoa topped with sliced avocado, cucumber ribbons, roasted chickpeas, fresh herbs, and a house-made green tahini dressing, scattered with seeds and edible flowers.', '850 DA', 'Salads & Bowls', '/images/unnamed.webp', array['Vegan','Gluten-Free'], 24),
  ('Mediterranean Feta Salad', 'Rocket, sheep''s feta, Kalamata olives, cherry tomatoes, herbs', 'A generous tangle of rocket and mixed leaves, Kalamata olives, halved cherry tomatoes, and thin-sliced cucumber, topped with crumbled sheep''s milk feta and dressed with lemon, extra virgin olive oil, and wild oregano.', '750 DA', 'Salads & Bowls', '/images/unnamed-1.webp', array['Vegetarian'], 25),
  ('Warm Roasted Grain Bowl', 'Farro, roasted vegetables, hummus, hazelnut dukkah', 'Warm farro and bulgur wheat topped with a rainbow of oven-roasted seasonal vegetables, a generous swoosh of house-made hummus, hazelnut dukkah, pomegranate molasses, and a handful of fresh herbs.', '800 DA', 'Salads & Bowls', '/images/unnamed-2.webp', array['Vegan'], 26),
  ('Chocolate Fondant', 'Warm dark chocolate, molten centre, vanilla bean ice cream', 'Individually baked 72% dark chocolate fondant — crackled on the outside, richly flowing within. Served immediately alongside a quenelle of house-made vanilla bean ice cream and a dusting of cacao.', '650 DA', 'Desserts & Cakes', '/images/unnamed-3.webp', array['Warm','Bestseller'], 27),
  ('Lotus Biscoff Cheesecake', 'Velvety baked cheesecake, Biscoff crust, caramel glaze', 'Velvety baked cheesecake on a buttery Lotus Biscoff crust, topped with a mirror-smooth caramel glaze and a whole Biscoff biscuit. Chilled overnight for a perfectly set, melt-in-the-mouth texture.', '700 DA', 'Desserts & Cakes', '/images/sealing.webp', array['Chef''s Pick'], 28),
  ('Pistachio & Raspberry Tart', 'Crisp pastry shell, pistachio frangipane, fresh raspberries', 'A crisp pâte sucrée shell filled with silky pistachio frangipane cream, adorned with fresh raspberries and a thin coat of apricot glaze. Finished with chopped pistachios and a sprig of fresh mint.', '600 DA', 'Desserts & Cakes', '/images/gallery-01.jpg', array['Seasonal'], 29),
  ('Ceremonial Matcha Latte', 'Ceremonial grade matcha, steamed oat milk, touch of raw honey', 'Premium ceremonial grade Japanese matcha, whisked to a smooth froth and topped with steamed oat milk poured in a delicate pattern. Subtly sweetened with raw honey. Available hot or iced.', '450 DA', 'Beverages', '/images/gallery-02.jpg', array['Vegan Option'], 30),
  ('Iced Hibiscus Rose', 'Hibiscus, rose water, fresh mint, lemon, sparkling water', 'A jewel-bright, naturally caffeine-free sipper. Cold-steeped hibiscus blended with rose water, fresh lemon, and a handful of mint, poured over ice and topped with a splash of sparkling water.', '350 DA', 'Beverages', '/images/gallery-04.jpg', array['Caffeine-Free','Bestseller'], 31),
  ('House Specialty Coffee', 'Single origin, prepared your way — espresso, flat white, cold brew', 'Sourced from single-origin Ethiopian beans, roasted to a medium-light profile. Available as espresso, flat white, cappuccino, Americano, or cold brew. All dairy and plant milks available.', '300 DA', 'Beverages', '/images/gallery-07.jpg', array[]::text[], 32),
  ('Maydi''s Signature Brunch', 'Poached eggs, smoked salmon, silky avocado on toasted sourdough', 'Two perfectly poached eggs draped over house-smoked salmon and silky avocado mash on toasted sourdough. Finished with a drizzle of lemon herb oil, capers, and microgreens. Served with a side dressed salad.', '950 DA', 'Brunch', '/images/gallery-01.jpg', array['Chef''s Pick','Bestseller'], 33),
  ('Garden Eggs Platter', 'Roasted seasonal vegetables, herb pesto, two poached eggs', 'A colourful medley of oven-roasted courgette, peppers, and cherry tomatoes, crowned with two poached eggs and a vibrant basil-pistachio pesto. Light, nourishing, and deeply satisfying.', '850 DA', 'Brunch', '/images/gallery-02.jpg', array['Vegetarian'], 34),
  ('Brioche French Toast', 'Thick-cut brioche, vanilla custard, maple syrup, fresh berries', 'Thick-cut brioche soaked overnight in a vanilla bean egg custard, pan-fried to a golden blush, served with warm maple syrup, a dusting of icing sugar, and a generous spoonful of seasonal berry compote.', '750 DA', 'Brunch', '/images/gallery-04.jpg', array['Sweet'], 35),
  ('Avocado Toast Deluxe', 'Sourdough, smashed avocado, cherry tomatoes, za''atar, chilli', 'Thick sourdough slices toasted to perfection, spread with seasoned avocado mash, halved cherry tomatoes, toasted pine nuts, and a flourish of za''atar. A squeeze of lemon ties it all together.', '650 DA', 'Toasts & Croissants', '/images/gallery-07.jpg', array['Vegan','Bestseller'], 36),
  ('Salmon Cream Cheese Toast', 'Whipped cream cheese, cold-smoked salmon, capers, dill', 'House-baked rye toast spread with whipped cream cheese blended with fresh dill, topped with silky cold-smoked salmon, briny capers, pickled red onion, and a crack of black pepper.', '700 DA', 'Toasts & Croissants', '/images/gallery-08.jpg', array[]::text[], 37),
  ('Butter Croissant', 'Freshly baked daily, served warm with house-made jam', 'Laminated in house with 84% French butter over three days. Baked fresh each morning until deeply golden. Served warm alongside house-made apricot jam and a curl of salted butter.', '350 DA', 'Toasts & Croissants', '/images/gallery-09.jpg', array['Fresh Daily'], 38),
  ('Almond Frangipane Croissant', 'Double-baked, almond cream filling, toasted flaked almonds', 'Our croissant taken one step further — filled with rich almond frangipane, double-baked for crisp caramelised layers, finished with toasted flaked almonds and a cloud of icing sugar.', '450 DA', 'Toasts & Croissants', '/images/gallery-10.jpg', array['Chef''s Pick'], 39),
  ('Green Goddess Bowl', 'Tri-colour quinoa, avocado, cucumber, herbs, green tahini', 'A nourishing base of tri-colour quinoa topped with sliced avocado, cucumber ribbons, roasted chickpeas, fresh herbs, and a house-made green tahini dressing, scattered with seeds and edible flowers.', '850 DA', 'Salads & Bowls', '/images/unnamed.webp', array['Vegan','Gluten-Free'], 40),
  ('Mediterranean Feta Salad', 'Rocket, sheep''s feta, Kalamata olives, cherry tomatoes, herbs', 'A generous tangle of rocket and mixed leaves, Kalamata olives, halved cherry tomatoes, and thin-sliced cucumber, topped with crumbled sheep''s milk feta and dressed with lemon, extra virgin olive oil, and wild oregano.', '750 DA', 'Salads & Bowls', '/images/unnamed-1.webp', array['Vegetarian'], 41),
  ('Warm Roasted Grain Bowl', 'Farro, roasted vegetables, hummus, hazelnut dukkah', 'Warm farro and bulgur wheat topped with a rainbow of oven-roasted seasonal vegetables, a generous swoosh of house-made hummus, hazelnut dukkah, pomegranate molasses, and a handful of fresh herbs.', '800 DA', 'Salads & Bowls', '/images/unnamed-2.webp', array['Vegan'], 42),
  ('Chocolate Fondant', 'Warm dark chocolate, molten centre, vanilla bean ice cream', 'Individually baked 72% dark chocolate fondant — crackled on the outside, richly flowing within. Served immediately alongside a quenelle of house-made vanilla bean ice cream and a dusting of cacao.', '650 DA', 'Desserts & Cakes', '/images/unnamed-3.webp', array['Warm','Bestseller'], 43),
  ('Lotus Biscoff Cheesecake', 'Velvety baked cheesecake, Biscoff crust, caramel glaze', 'Velvety baked cheesecake on a buttery Lotus Biscoff crust, topped with a mirror-smooth caramel glaze and a whole Biscoff biscuit. Chilled overnight for a perfectly set, melt-in-the-mouth texture.', '700 DA', 'Desserts & Cakes', '/images/sealing.webp', array['Chef''s Pick'], 44),
  ('Pistachio & Raspberry Tart', 'Crisp pastry shell, pistachio frangipane, fresh raspberries', 'A crisp pâte sucrée shell filled with silky pistachio frangipane cream, adorned with fresh raspberries and a thin coat of apricot glaze. Finished with chopped pistachios and a sprig of fresh mint.', '600 DA', 'Desserts & Cakes', '/images/gallery-01.jpg', array['Seasonal'], 45),
  ('Ceremonial Matcha Latte', 'Ceremonial grade matcha, steamed oat milk, touch of raw honey', 'Premium ceremonial grade Japanese matcha, whisked to a smooth froth and topped with steamed oat milk poured in a delicate pattern. Subtly sweetened with raw honey. Available hot or iced.', '450 DA', 'Beverages', '/images/gallery-02.jpg', array['Vegan Option'], 46),
  ('Iced Hibiscus Rose', 'Hibiscus, rose water, fresh mint, lemon, sparkling water', 'A jewel-bright, naturally caffeine-free sipper. Cold-steeped hibiscus blended with rose water, fresh lemon, and a handful of mint, poured over ice and topped with a splash of sparkling water.', '350 DA', 'Beverages', '/images/gallery-04.jpg', array['Caffeine-Free','Bestseller'], 47),
  ('House Specialty Coffee', 'Single origin, prepared your way — espresso, flat white, cold brew', 'Sourced from single-origin Ethiopian beans, roasted to a medium-light profile. Available as espresso, flat white, cappuccino, Americano, or cold brew. All dairy and plant milks available.', '300 DA', 'Beverages', '/images/gallery-07.jpg', array[]::text[], 48);

notify pgrst, 'reload schema';

select count(*) as menu_items from public.menu_items;
